version: '3'
services:
  unifi-cam-proxy:
    build: .
    container_name: unifi-cam-proxy
    volumes:
      - './client.pem:/client.pem'
    environment:
      - "HOST=192.168.103.180"
      - "TOKEN=UojOceUtnvtaxpiY"
      - "RTSP_URL=rtsp://freja.hiof.no:1935/rtplive/definst/hessdalen03.stream"
    restart: always
  unifi-video-controller:
    image:  pducharme/unifi-video-controller
    container_name: unifi-video-controller
    ports:
      - 1935:1935
      - 6666:6666
      - 7004:7004
      - 7080:7080
      - 7442:7442
      - 7443:7443
      - 7444:7444
      - 7445:7445
      - 7446:7446
      - 7447:7447
    volumes:
      - ./run/data:/var/lib/unifi-video
      - ./run/videos:/var/lib/unifi-video/videos
    environment:
      - TZ=America/Los_Angeles
      - DEBUG=1
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
  unifi-protect:
    container_name: unifi-protect
    ports:
        - '7080:7080'
        - '7442:7442'
        - '7443:7443'
        - '7444:7444'
        - '7447:7447'
        - '7550:7550'
    volumes:
        - './run/protect/data:/srv/unifi-protect'
        - './run/protect/db:/var/lib/postgresql/10/main'
        - './run/protect/db_config:/etc/postgresql/10/main'
        - './run/protect/config.json:/usr/share/unifi-protect/app/config/config.json'
    environment:
        - TZ=America/Los_Angeles
        - PUID=999
        - PGID=999
        - PUID_POSTGRES=102
        - PGID_POSTGRES=104
    image: fryfrog/unifi-protect
  frigate:
    image: blakeblackshear/frigate:stable-amd64
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
      - ./run/frigate:/config
    ports:
      - "5000:5000"
